title: Ifeanyi Enyoghasi Data Analytics Portfolio
logo: ab79678e-d399-4c8f-a129-32878c9a390f.jpeg
description:  Experienced Data Analyst specialising in SQL, Power BI, Azure and Data Visualisation. Explore my portfolio of dashboards, analytics projects, data models and business intelligence solutions that transform complex data into actionable insights.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
